// Mocks generated by Mockito 5.4.4 from annotations
// in fortune_gallery/test/view_model/manage_fortune_vm/manage_fortune_vm_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fortune_gallery/_lib.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FortuneRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFortuneRepo extends _i1.Mock implements _i2.FortuneRepo {
  MockFortuneRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.BaseResponse<dynamic>> addFortune(_i2.FortuneModel? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFortune,
          [note],
        ),
        returnValue: _i3.Future<_i2.BaseResponse<dynamic>>.value(
            _FakeBaseResponse_0<dynamic>(
          this,
          Invocation.method(
            #addFortune,
            [note],
          ),
        )),
      ) as _i3.Future<_i2.BaseResponse<dynamic>>);

  @override
  _i3.Future<_i2.BaseResponse<_i2.FortuneModel>> updateFortune(
          _i2.FortuneModel? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFortune,
          [note],
        ),
        returnValue: _i3.Future<_i2.BaseResponse<_i2.FortuneModel>>.value(
            _FakeBaseResponse_0<_i2.FortuneModel>(
          this,
          Invocation.method(
            #updateFortune,
            [note],
          ),
        )),
      ) as _i3.Future<_i2.BaseResponse<_i2.FortuneModel>>);

  @override
  _i3.Future<_i2.BaseResponse<int>> deleteFortune(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFortune,
          [id],
        ),
        returnValue:
            _i3.Future<_i2.BaseResponse<int>>.value(_FakeBaseResponse_0<int>(
          this,
          Invocation.method(
            #deleteFortune,
            [id],
          ),
        )),
      ) as _i3.Future<_i2.BaseResponse<int>>);

  @override
  _i3.Future<_i2.BaseResponse<_i2.FortuneModel>> getSingleFortune(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSingleFortune,
          [id],
        ),
        returnValue: _i3.Future<_i2.BaseResponse<_i2.FortuneModel>>.value(
            _FakeBaseResponse_0<_i2.FortuneModel>(
          this,
          Invocation.method(
            #getSingleFortune,
            [id],
          ),
        )),
      ) as _i3.Future<_i2.BaseResponse<_i2.FortuneModel>>);

  @override
  _i3.Future<_i2.BaseResponse<List<_i2.FortuneModel>>> getAllFortune({
    int? startFrom,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFortune,
          [],
          {
            #startFrom: startFrom,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<_i2.BaseResponse<List<_i2.FortuneModel>>>.value(
            _FakeBaseResponse_0<List<_i2.FortuneModel>>(
          this,
          Invocation.method(
            #getAllFortune,
            [],
            {
              #startFrom: startFrom,
              #limit: limit,
            },
          ),
        )),
      ) as _i3.Future<_i2.BaseResponse<List<_i2.FortuneModel>>>);

  @override
  _i3.Future<_i2.BaseResponse<int>> totalTableCount() => (super.noSuchMethod(
        Invocation.method(
          #totalTableCount,
          [],
        ),
        returnValue:
            _i3.Future<_i2.BaseResponse<int>>.value(_FakeBaseResponse_0<int>(
          this,
          Invocation.method(
            #totalTableCount,
            [],
          ),
        )),
      ) as _i3.Future<_i2.BaseResponse<int>>);
}
